// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1VVvuwVPbCygNMLQ_rlnzBwasZpTFel0',
    appId: '1:400709871551:web:fcad2d70daf1c29788e30a',
    messagingSenderId: '400709871551',
    projectId: 'flutterdb-12f49',
    authDomain: 'flutterdb-12f49.firebaseapp.com',
    storageBucket: 'flutterdb-12f49.appspot.com',
    measurementId: 'G-L2VH0RPLRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD7qvFexpYKQL_rtz9kR98jBY_ak4PRC8',
    appId: '1:400709871551:android:4084f88f899dbc5c88e30a',
    messagingSenderId: '400709871551',
    projectId: 'flutterdb-12f49',
    storageBucket: 'flutterdb-12f49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyvMMIKGN3Hj-5QRxt5s7N6GevawM0s4w',
    appId: '1:400709871551:ios:f4d530b9019ef34588e30a',
    messagingSenderId: '400709871551',
    projectId: 'flutterdb-12f49',
    storageBucket: 'flutterdb-12f49.appspot.com',
    iosBundleId: 'com.example.expenseMangamentSystem',
  );
}
